name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_SKIP: "*musllinux*" # musl では spglib がうまく動かない
          CIBW_ARCHS: "auto64"
          CIBW_BEFORE_BUILD_LINUX: "rm -rf {project}/build"
          CIBW_BEFORE_BUILD_MACOS: "rm -rf {project}/build"
          CIBW_BEFORE_BUILD_WINDOWS: "if exist build rmdir /s /q build"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.15
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest
          # テストは最新の Python でのみ実行
          CIBW_TEST_SKIP: "cp{36,37,38,39,310,311}-*"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

