name: Test on macOS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # 任意のバージョン

      - name: Set CMAKE_PREFIX_PATH environment variable
        run: echo "CMAKE_PREFIX_PATH=$(python -m pybind11 --cmakedir)" >> $GITHUB_ENV

      - name: Install package
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --index-url https://test.pypi.org/simple/ \
                      --extra-index-url https://pypi.org/simple \
                      graph-id-core
          pip install graph-id-core
